// Generated by CoffeeScript 1.3.3
(function() {
  var DEFAULT_PROJ, OSM_GEO_JSON, OSM_PROJ, deleteLayer, disableToolbox, enableToolbox, handleLayerRowSelectRequest, handleNewLayerRequest, initBasicRestrictedEditableMap, initEditableMap, initEditor, initEditorLayout, saveCurrentLayerFeatures, useLineTool, useMoveTool, useNoTool, usePathTool, usePointTool, usePolygonTool, useResizeTool, useRotateTool, useTool;

  Ext.Loader.setConfig({
    enabled: true
  });

  Ext.Loader.setPath('Ext.ux', './js/ux');

  Ext.require('Ext.ux.layout.Center');

  Ext.define('Layer', {
    extend: 'Ext.data.Model',
    idgen: 'uuid',
    fields: [
      {
        name: 'id',
        type: 'string'
      }, {
        name: 'name',
        type: 'string',
        defaultValue: 'Untitled'
      }, {
        name: 'features',
        type: 'string'
      }, {
        name: 'created',
        type: 'date'
      }, {
        name: 'updated',
        type: 'date'
      }
    ],
    proxy: {
      type: 'localstorage',
      id: 'localpoints-layers'
    }
  });

  Ext.define('Feature', {
    extend: 'Ext.data.Model',
    idgen: 'uuid',
    fields: [
      {
        name: 'id',
        type: 'string'
      }, {
        name: 'name',
        type: 'string',
        defaultValue: 'Feature'
      }, {
        name: 'type',
        type: 'string'
      }, {
        name: 'created',
        type: 'date'
      }, {
        name: 'updated',
        type: 'date'
      }
    ],
    proxy: {
      type: 'memory',
      id: 'localpoints-layerfeatures'
    }
  });

  DEFAULT_PROJ = new OpenLayers.Projection('EPSG:4326');

  OSM_PROJ = new OpenLayers.Projection('EPSG:900913');

  OSM_GEO_JSON = new OpenLayers.Format.GeoJSON({
    internalProjection: OSM_PROJ,
    externalProjection: DEFAULT_PROJ
  });

  Ext.define('CurrentLayer', {
    singleton: true,
    record: null
  });

  useTool = function(selectedControlName, controls) {
    var control, name, _results;
    _results = [];
    for (name in controls) {
      control = controls[name];
      if (name === selectedControlName) {
        _results.push(control.activate());
      } else {
        _results.push(control.deactivate());
      }
    }
    return _results;
  };

  usePointTool = function(controls) {
    return useTool('point', controls);
  };

  useLineTool = function(controls) {
    return useTool('line', controls);
  };

  usePolygonTool = function(controls) {
    return useTool('polygon', controls);
  };

  usePathTool = function(controls) {
    controls.modify.mode = OpenLayers.Control.ModifyFeature.RESHAPE;
    return useTool('modify', controls);
  };

  useRotateTool = function(controls) {
    controls.modify.mode = OpenLayers.Control.ModifyFeature.RESHAPE | OpenLayers.Control.ModifyFeature.ROTATE;
    return useTool('modify', controls);
  };

  useResizeTool = function(controls) {
    controls.modify.mode = OpenLayers.Control.ModifyFeature.RESHAPE | OpenLayers.Control.ModifyFeature.RESIZE;
    return useTool('modify', controls);
  };

  useMoveTool = function(controls) {
    controls.modify.mode = OpenLayers.Control.ModifyFeature.RESHAPE | OpenLayers.Control.ModifyFeature.DRAG;
    return useTool('modify', controls);
  };

  useNoTool = function(controls) {
    var control, name, _results;
    _results = [];
    for (name in controls) {
      control = controls[name];
      _results.push(control.deactivate());
    }
    return _results;
  };

  disableToolbox = function() {
    var button, buttons, _i, _len, _results;
    buttons = Ext.getCmp('tools-panel').query('button');
    _results = [];
    for (_i = 0, _len = buttons.length; _i < _len; _i++) {
      button = buttons[_i];
      button.blur();
      button.disable();
      _results.push(button.toggle(false, true));
    }
    return _results;
  };

  enableToolbox = function() {
    var button, buttons, _i, _len, _results;
    buttons = Ext.getCmp('tools-panel').query('button');
    _results = [];
    for (_i = 0, _len = buttons.length; _i < _len; _i++) {
      button = buttons[_i];
      _results.push(button.enable());
    }
    return _results;
  };

  deleteLayer = function(layerStore, featureStore, vectorLayer, tools) {
    if (CurrentLayer.record !== null) {
      layerStore.remove(CurrentLayer.record);
      CurrentLayer.record = null;
      disableToolbox();
      vectorLayer.removeAllFeatures();
      useNoTool(tools);
      layerStore.sync();
      if (layerStore.count() === 0) {
        return Ext.getCmp('layerDeleteButton').blur().disable();
      }
    }
  };

  handleNewLayerRequest = function(button, event, layerStore) {
    var date;
    date = new Date();
    layerStore.add(layerStore.create({
      name: 'Untitled',
      features: '',
      created: date,
      updated: date
    }));
    return layerStore.sync();
  };

  handleLayerRowSelectRequest = function(selection, record, opts, featureStore, vectorLayer) {
    var features, geojson;
    vectorLayer.removeAllFeatures();
    enableToolbox();
    if (Ext.getCmp('layerDeleteButton').isDisabled()) {
      Ext.getCmp('layerDeleteButton').enable();
    }
    if (record.length > 0) {
      CurrentLayer.record = record[0];
      geojson = record[0].get('features');
      if (geojson !== '') {
        features = OSM_GEO_JSON.read(geojson);
        return vectorLayer.addFeatures(features);
      }
    }
  };

  saveCurrentLayerFeatures = function(features) {
    var geojson;
    if (CurrentLayer.record !== void 0 && CurrentLayer.record !== null && features.length > 0) {
      geojson = OSM_GEO_JSON.write(features);
      CurrentLayer.record.set('features', geojson);
      return CurrentLayer.record.save();
    }
  };

  initEditableMap = function(map, baseLayer, vectorLayer, tools, zoomToExtent) {
    var control, name, save;
    map.addLayer(baseLayer);
    map.setBaseLayer(baseLayer);
    map.addLayer(vectorLayer);
    save = function(e) {
      return saveCurrentLayerFeatures(vectorLayer.features);
    };
    vectorLayer.events.register('featureadded', null, save);
    vectorLayer.events.register('featureremoved', null, save);
    vectorLayer.events.register('featuremodified', null, save);
    for (name in tools) {
      control = tools[name];
      map.addControl(control);
    }
    map.zoomToExtent(zoomToExtent);
    return map;
  };

  initBasicRestrictedEditableMap = function(id, vectorLayer, tools, zoomToExtent) {
    var map, options, osm;
    options = {
      restrictedExtent: zoomToExtent
    };
    map = new OpenLayers.Map(id, options);
    osm = new OpenLayers.Layer.OSM();
    return initEditableMap(map, osm, vectorLayer, tools, zoomToExtent);
  };

  initEditorLayout = function(layerStore, featureStore, vectorLayer, tools, zoomToExtent) {
    var drawToolsPanel, featuresColumns, featuresGrid, featuresPanel, featuresToolbar, layersColumns, layersGrid, layersPanel, layersToolbar, mapPanel, modifyToolsPanel, toolsPanel;
    layersToolbar = {
      tbar: [
        {
          text: 'New',
          handler: function(b, e) {
            return handleNewLayerRequest(b, e, layerStore);
          }
        }, {
          text: 'Delete',
          id: 'layerDeleteButton',
          focusOnToFront: false,
          enableToggle: false,
          disabled: true,
          listeners: {
            click: function() {
              return deleteLayer(layerStore, featureStore, vectorLayer, tools);
            }
          }
        }
      ],
      border: false
    };
    layersColumns = [
      {
        id: 'layer-name',
        text: 'Name',
        sortable: true,
        dataIndex: 'name',
        field: {
          xtype: 'textfield',
          allowBlank: false
        }
      }, {
        id: 'layer-updated',
        text: 'Updated',
        sortable: true,
        dataIndex: 'updated'
      }, {
        id: 'layer-created',
        text: 'Created',
        sortable: true,
        dataIndex: 'created'
      }
    ];
    layersGrid = {
      xtype: 'gridpanel',
      border: false,
      selType: 'rowmodel',
      plugins: [
        Ext.create('Ext.grid.plugin.CellEditing', {
          clicksToEdit: 2,
          listeners: {
            edit: {
              element: 'el',
              fn: function(editor, e) {
                return e.record.save();
              }
            }
          }
        })
      ],
      store: layerStore,
      listeners: {
        selectionchange: function(m, r, o) {
          return handleLayerRowSelectRequest(m, r, o, featureStore, vectorLayer);
        }
      },
      columns: layersColumns
    };
    layersPanel = {
      id: 'layers-panel',
      title: 'Layers',
      region: 'north',
      height: 200,
      autoScroll: true,
      margins: '2 0 2 0',
      items: [layersToolbar, layersGrid]
    };
    featuresToolbar = {
      tbar: [
        {
          text: 'Delete'
        }, {
          text: 'Delete all'
        }
      ],
      border: false
    };
    featuresColumns = [
      {
        id: 'feature-name',
        text: 'Name',
        sortable: true,
        dataIndex: 'name',
        field: {
          xtype: 'textfield',
          allowBlank: false
        }
      }, {
        id: 'feature-type',
        text: 'Type',
        sortable: true,
        dataIndex: 'type'
      }, {
        id: 'feature-updated',
        text: 'Updated',
        sortable: true,
        dataIndex: 'updated'
      }, {
        id: 'feature-created',
        text: 'Created',
        sortable: true,
        dataIndex: 'created'
      }
    ];
    featuresGrid = {
      xtype: 'gridpanel',
      border: false,
      selType: 'rowmodel',
      store: featureStore,
      plugins: [
        Ext.create('Ext.grid.plugin.CellEditing', {
          clicksToEdit: 2
        })
      ],
      columns: featuresColumns
    };
    featuresPanel = {
      id: 'features-panel',
      title: 'Features',
      region: 'center',
      autoScroll: true,
      margins: '2 0 2 0',
      items: [featuresToolbar, featuresGrid]
    };
    drawToolsPanel = {
      id: 'draw-tools-panel',
      title: 'Draw',
      region: 'north',
      border: false,
      layout: 'ux.center',
      widthRatio: 0.80,
      autoHeight: true,
      frame: true,
      items: [
        {
          xtype: 'buttongroup',
          columns: 3,
          defaults: {
            scale: 'small'
          },
          items: [
            {
              xtype: 'button',
              disabled: true,
              text: 'Point',
              enableToggle: true,
              toggleGroup: 'toolbox',
              toggleHandler: function(button, state) {
                if (state) {
                  return usePointTool(tools);
                } else {
                  return useNoTool(tools);
                }
              }
            }, {
              xtype: 'button',
              disabled: true,
              text: 'Line',
              enableToggle: true,
              toggleGroup: 'toolbox',
              toggleHandler: function(button, state) {
                if (state) {
                  return useLineTool(tools);
                } else {
                  return useNoTool(tools);
                }
              }
            }, {
              xtype: 'button',
              disabled: true,
              text: 'Polygon',
              enableToggle: true,
              toggleGroup: 'toolbox',
              toggleHandler: function(button, state) {
                if (state) {
                  return usePolygonTool(tools);
                } else {
                  return useNoTool(tools);
                }
              }
            }
          ]
        }
      ]
    };
    modifyToolsPanel = {
      id: 'modify-tools-panel',
      title: 'Modify',
      region: 'north',
      border: false,
      layout: 'ux.center',
      widthRatio: 0.80,
      autoHeight: true,
      frame: true,
      items: [
        {
          xtype: 'buttongroup',
          columns: 4,
          defaults: {
            scale: 'small'
          },
          items: [
            {
              xtype: 'button',
              disabled: true,
              text: 'Path',
              enableToggle: true,
              toggleGroup: 'toolbox',
              toggleHandler: function(button, state) {
                if (state) {
                  return usePathTool(tools);
                } else {
                  return useNoTool(tools);
                }
              }
            }, {
              xtype: 'button',
              disabled: true,
              text: 'Rotate',
              enableToggle: true,
              toggleGroup: 'toolbox',
              toggleHandler: function(button, state) {
                if (state) {
                  return useRotateTool(tools);
                } else {
                  return useNoTool(tools);
                }
              }
            }, {
              xtype: 'button',
              disabled: true,
              text: 'Resize',
              enableToggle: true,
              toggleGroup: 'toolbox',
              toggleHandler: function(button, state) {
                if (state) {
                  return useResizeTool(tools);
                } else {
                  return useNoTool(tools);
                }
              }
            }, {
              xtype: 'button',
              disabled: true,
              text: 'Move',
              enableToggle: true,
              toggleGroup: 'toolbox',
              toggleHandler: function(button, state) {
                if (state) {
                  return useMoveTool(tools);
                } else {
                  return useNoTool(tools);
                }
              }
            }
          ]
        }
      ]
    };
    toolsPanel = {
      id: 'tools-panel',
      title: 'Toolbox',
      region: 'south',
      margins: '2 0 0 0',
      bodyStyle: 'padding: 4px',
      items: [drawToolsPanel, modifyToolsPanel]
    };
    mapPanel = {
      id: 'map-panel',
      region: 'center',
      layout: 'fit',
      margins: '5 5 5 0',
      activeItem: 0,
      border: false,
      items: []
    };
    Ext.create('Ext.Viewport', {
      layout: 'border',
      title: 'localpoints on a map',
      items: [
        {
          xtype: 'box',
          id: 'header',
          region: 'north',
          html: '<h1>localpoints on a map</h1>',
          height: 30
        }, {
          layout: 'border',
          id: 'layout-browser',
          region: 'west',
          border: false,
          split: true,
          margins: '5 0 5 5',
          width: 300,
          minSize: 160,
          maxSize: 400,
          items: [layersPanel, featuresPanel, toolsPanel]
        }, mapPanel
      ],
      renderTo: Ext.getBody()
    });
    return initBasicRestrictedEditableMap('map-panel-body', vectorLayer, tools, zoomToExtent);
  };

  initEditor = function(layerStore, featureStore) {
    var extent, featureModifier, renderer, tools, vectors;
    layerStore.load();
    OpenLayers.Feature.Vector.style['default']['strokeWidth'] = '2';
    renderer = OpenLayers.Util.getParameters(window.location.href).renderer;
    vectors = new OpenLayers.Layer.Vector("Vector Layer", {
      renderers: renderer ? [renderer] : OpenLayers.Layer.Vector.prototype.renderers
    });
    featureModifier = new OpenLayers.Control.ModifyFeature(vectors);
    tools = {
      point: new OpenLayers.Control.DrawFeature(vectors, OpenLayers.Handler.Point),
      line: new OpenLayers.Control.DrawFeature(vectors, OpenLayers.Handler.Path),
      polygon: new OpenLayers.Control.DrawFeature(vectors, OpenLayers.Handler.Polygon),
      modify: featureModifier
    };
    extent = new OpenLayers.Bounds(174.6, -37, 175, -36.8).transform(DEFAULT_PROJ, OSM_PROJ);
    return initEditorLayout(layerStore, featureStore, vectors, tools, extent);
  };

  Ext.onReady(function() {
    var featureStore, layerStore;
    layerStore = Ext.create('Ext.data.Store', {
      model: 'Layer'
    });
    featureStore = Ext.create('Ext.data.Store', {
      model: 'Feature'
    });
    return initEditor(layerStore, featureStore);
  });

}).call(this);
